./project_week2.py "breast cancer"
./project_week2.py "stomach cancer"
./project_week2.py "alzheimer"
./project_week2.py "parkinson"
./project_week2.py "diabetes"
./project_week2.py "dyslexia"
./project_week2.py "heart disease"
./project_week2.py "leukemia"
./project_week2.py "osteoporosis"
./project_week2.py "lung cancer"
./project_week2.py "blindness"
